FROM ubuntu:17.04
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y moreutils curl
RUN chronic apt-get install -y afnix
RUN chronic apt-get install -y algol68g
RUN chronic apt-get install -y aplus-fsf
RUN chronic apt-get install -y aspectc++
RUN chronic apt-get install -y aspectj
RUN chronic apt-get install -y asymptote
RUN chronic apt-get install -y ats2-lang
RUN chronic apt-get install -y bash
RUN chronic apt-get install -y bc
RUN chronic apt-get install -y bf
RUN chronic apt-get install -y bison
RUN chronic apt-get install -y bsdgames
RUN chronic apt-get install -y cduce
RUN chronic apt-get install -y clisp
RUN chronic apt-get install -y clojure
RUN chronic apt-get install -y cmake
RUN chronic apt-get install -y coffeescript
RUN chronic apt-get install -y dafny
RUN chronic apt-get install -y dc
RUN chronic apt-get install -y ecere-dev
RUN chronic apt-get install -y elixir
RUN chronic apt-get install -y emacs24
RUN chronic apt-get install -y erlang
RUN chronic apt-get install -y f2c
RUN chronic apt-get install -y flex
RUN chronic apt-get install -y fp-compiler
RUN chronic apt-get install -y fsharp
RUN chronic apt-get install -y g++
RUN chronic apt-get install -y gambas3-script
RUN chronic apt-get install -y gap
RUN chronic apt-get install -y gawk
RUN chronic apt-get install -y gcc
RUN chronic apt-get install -y gdb
RUN chronic apt-get install -y gdc
RUN chronic apt-get install -y genius
RUN chronic apt-get install -y gforth
RUN chronic apt-get install -y gfortran
RUN chronic apt-get install -y ghc
RUN chronic apt-get install -y ghostscript
RUN chronic apt-get install -y gnat
RUN chronic apt-get install -y gnu-smalltalk
RUN chronic apt-get install -y gnuplot
RUN chronic apt-get install -y gobjc
RUN chronic apt-get install -y golang
RUN chronic apt-get install -y gpt
RUN chronic apt-get install -y gri
RUN chronic apt-get install -y groff
RUN chronic apt-get install -y groovy
RUN chronic apt-get install -y guile-2.0
RUN chronic apt-get install -y gzip
RUN chronic apt-get install -y haxe
RUN chronic apt-get install -y icont
RUN chronic apt-get install -y iconx
RUN chronic apt-get install -y intercal
RUN chronic apt-get install -y iverilog
RUN chronic apt-get install -y jasmin-sable
RUN chronic apt-get install -y jq
RUN chronic apt-get install -y julia
RUN chronic apt-get install -y ksh
RUN chronic apt-get install -y libgd-dev
RUN chronic apt-get install -y libpng-dev
RUN chronic apt-get install -y lisaac
RUN chronic apt-get install -y livescript
RUN chronic apt-get install -y llvm
RUN chronic apt-get install -y lua5.3
RUN chronic apt-get install -y m4
RUN chronic apt-get install -y make
RUN chronic apt-get install -y maxima
RUN chronic apt-get install -y minizinc
RUN chronic apt-get install -y mlton
RUN chronic apt-get install -y mono-devel
RUN chronic apt-get install -y mono-mcs
RUN chronic apt-get install -y mono-vbnc
RUN chronic apt-get install -y nasm
RUN chronic apt-get install -y neko
RUN chronic apt-get install -y nescc
RUN chronic apt-get install -y nickle
RUN chronic apt-get install -y nim
RUN chronic apt-get install -y node-typescript
RUN chronic apt-get install -y nodejs
RUN chronic apt-get install -y ocaml
RUN chronic apt-get install -y octave
RUN chronic apt-get install -y open-cobol
RUN chronic apt-get install -y openjdk-8-jdk
RUN chronic apt-get install -y pakcs
RUN chronic apt-get install -y pari-gp
RUN chronic apt-get install -y parser3-cgi
RUN chronic apt-get install -y perl
RUN chronic apt-get install -y php-cli
RUN chronic apt-get install -y pike8.0
RUN chronic apt-get install -y python
RUN chronic apt-get install -y r-base
RUN chronic apt-get install -y rakudo
RUN chronic apt-get install -y ratfor
RUN chronic apt-get install -y rc
RUN chronic apt-get install -y regina-rexx
RUN chronic apt-get install -y ruby
RUN chronic apt-get install -y ruby-mustache
RUN chronic apt-get install -y rustc
RUN chronic apt-get install -y scala
RUN chronic apt-get install -y scilab
RUN chronic apt-get install -y sed
RUN chronic apt-get install -y slsh
RUN chronic apt-get install -y spin
RUN chronic apt-get install -y squirrel3
RUN chronic apt-get install -y swi-prolog
RUN chronic apt-get install -y tcl
RUN chronic apt-get install -y tcsh
RUN chronic apt-get install -y valac
RUN chronic apt-get install -y vim
RUN chronic apt-get install -y xsltproc
RUN chronic apt-get install -y yabasic
RUN chronic apt-get install -y yorick
RUN chronic apt-get install -y zoem
RUN chronic apt-get install -y zsh
ENV PATH /usr/games:$PATH
ADD . /usr/local/share/quine-relay
WORKDIR /usr/local/share/quine-relay
RUN make -C vendor
CMD make check -j 10000
